//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSF_ThietLapWebsite
    {
        public int id { get; set; }
        public string tenwebsite { get; set; }
        public string logo { get; set; }
        public string slogan { get; set; }
        public string hotline { get; set; }
        public string hotline_hotro { get; set; }
        public string hotline_dichvu { get; set; }
        public string facebook { get; set; }
        public string diachi { get; set; }
        public string tencongty { get; set; }
        public string thongtinbosung { get; set; }
        public Nullable<bool> hienthi_logo { get; set; }
        public string email { get; set; }
    }
}
