//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_DonHang()
        {
            this.QC_Thuoc_DonHang = new HashSet<QC_Thuoc_DonHang>();
        }
    
        public int id { get; set; }
        public Nullable<int> idkhachhang { get; set; }
        public System.DateTime ngaydathang { get; set; }
        public Nullable<decimal> thanhtiensaugiam { get; set; }
        public Nullable<decimal> sotiengiam { get; set; }
        public Nullable<decimal> thanhtientruocgiam { get; set; }
        public string madonhang { get; set; }
        public string ghichu { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public string motaxuly { get; set; }
        public Nullable<int> idphuongthucthanhtoan { get; set; }
        public Nullable<int> idmagiamgia { get; set; }
        public string diachinhanhang { get; set; }
    
        public virtual QC_KhachHang QC_KhachHang { get; set; }
        public virtual QC_PhuongThucThanhToan QC_PhuongThucThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_Thuoc_DonHang> QC_Thuoc_DonHang { get; set; }
    }
}
