//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_Gopy_KhieuNai
    {
        public int id { get; set; }
        public Nullable<int> idkhachhang { get; set; }
        public string noidunggopy { get; set; }
        public string noidungkhieunai { get; set; }
        public Nullable<System.DateTime> ngaygopy { get; set; }
        public string noidungphanhoi { get; set; }
        public Nullable<System.DateTime> ngayphanhoi { get; set; }
    
        public virtual QC_KhachHang QC_KhachHang { get; set; }
    }
}
