//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_KhachHang_Nhom
    {
        public int id { get; set; }
        public Nullable<int> idnhom { get; set; }
        public Nullable<int> idkhachhang { get; set; }
    
        public virtual QC_KhachHang QC_KhachHang { get; set; }
        public virtual QC_NhomKhachHang QC_NhomKhachHang { get; set; }
    }
}
