//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_KhachHang()
        {
            this.QC_Gopy_KhieuNai = new HashSet<QC_Gopy_KhieuNai>();
            this.QC_KhachHang_Nhom = new HashSet<QC_KhachHang_Nhom>();
            this.QC_DonHang = new HashSet<QC_DonHang>();
        }
    
        public int id { get; set; }
        public string tendaydu { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public string dienthoai { get; set; }
        public string diachi { get; set; }
        public string anhdaidien { get; set; }
        public Nullable<System.DateTime> ngaydangky { get; set; }
        public Nullable<int> diemtichluy { get; set; }
        public Nullable<bool> kichhoat { get; set; }
        public string makichhoat { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_Gopy_KhieuNai> QC_Gopy_KhieuNai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_KhachHang_Nhom> QC_KhachHang_Nhom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_DonHang> QC_DonHang { get; set; }
    }
}
