//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_MaGiamGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_MaGiamGia()
        {
            this.QC_DoiTuong_MaGiamGia = new HashSet<QC_DoiTuong_MaGiamGia>();
        }
    
        public int id { get; set; }
        public string tenma { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public Nullable<int> idloaigiamgia { get; set; }
        public Nullable<int> idkieudoituong { get; set; }
        public Nullable<int> solansudung { get; set; }
        public Nullable<bool> kichhoat { get; set; }
        public Nullable<decimal> giatri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_DoiTuong_MaGiamGia> QC_DoiTuong_MaGiamGia { get; set; }
        public virtual QC_KieuDoiTuong QC_KieuDoiTuong { get; set; }
        public virtual QC_LoaiGiamGia QC_LoaiGiamGia { get; set; }
    }
}
