//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_Slider
    {
        public int id { get; set; }
        public string tieudechinh { get; set; }
        public string tieudephu { get; set; }
        public string duongdananh { get; set; }
        public string duonglink { get; set; }
        public Nullable<int> thutu { get; set; }
    }
}
