//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_Thuoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QC_Thuoc()
        {
            this.QC_Thuoc_DonHang = new HashSet<QC_Thuoc_DonHang>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public string anhdaidien { get; set; }
        public Nullable<int> idloaithuoc { get; set; }
        public string hansudung { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<int> iddonvi { get; set; }
        public Nullable<bool> tinhtrang { get; set; }
        public string mota { get; set; }
        public Nullable<int> idbiendonggia { get; set; }
        public Nullable<bool> docquyen { get; set; }
        public Nullable<bool> uudai { get; set; }
        public Nullable<bool> sanphammoi { get; set; }
    
        public virtual QC_BienDongGia QC_BienDongGia { get; set; }
        public virtual QC_DonViThuoc QC_DonViThuoc { get; set; }
        public virtual QC_LoaiThuoc QC_LoaiThuoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QC_Thuoc_DonHang> QC_Thuoc_DonHang { get; set; }
    }
}
