//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC_YKienKhachHang
    {
        public int id { get; set; }
        public string tenkhachhang { get; set; }
        public string noidung { get; set; }
        public Nullable<bool> hienthi { get; set; }
        public Nullable<int> thutu { get; set; }
        public string anhdaidien { get; set; }
        public string thongtinthem { get; set; }
    }
}
